#!/usr/bin/env bash


echo "Installing embeded VistaMart"

echo "Executing oracle tweaking"

echo "Setting kernel parameters in /etc/sysctl.conf"
command echo -e "
#oracle tuning
kernel.shmmni = 4096
kernel.sem = 250 32000 100 128
fs.file-max = 6815744
fs.aio-max-nr = 1048576
net.ipv4.ip_local_port_range = 9000 65500
net.core.rmem_default = 1048576
net.core.rmem_max = 4194304
net.core.wmem_default = 262144
net.core.wmem_max = 1048576
" >> /etc/sysctl.conf
echo "-> Ok"
echo "Applying..."
command sysctl -p /etc/sysctl.conf
echo "-> Ok"

echo "Setting oracle limit in /etc/security/limits.conf"
command echo -e "
oracle soft nproc 2047
oracle hard nproc 16384
oracle soft nofile 1024
oracle hard nofile 65536
oracle soft stack 10240
" >> /etc/security/limits.conf
echo "-> Ok"

echo "Setting pam_limits..."
command echo -e "
session required pam_limits.so
" >> /etc/pam.d/login
echo "-> Ok"

echo "Setting oracle user limit..."
command echo -e "
if [ $USER = "oracle" ]; then
    if [ $SHELL = "/bin/ksh" ]; then
        ulimit -u 16384
        ulimit -n 65536
    else
        ulimit -u 16384 -n 65536
    fi
fi
" >> /etc/profile
echo "-> Ok"

echo "Modifying tmpfs parameters..."
#fstab edit
sed -i -e 's/(^tmpfs.*)defaults(.*)/#1size=3g#2/g' /etc/fstab

echo "Creating symbolic link for hostname..."
ln -s /bin/hostname /usr/bin/hostname


command mkdir -p /opt/vfk_install_files/VM
command chown -R infovista:infovista /opt/vfk_install_files/
command mv -v /tmp/VistaMart-5.0-linux.zip /opt/vfk_install_files/VM/
command cd /opt/vfk_install_files/VM/ && unzip VistaMart-5.0-linux.zip
command chmod +x setup.sh

#Setup install path
# => /opt/InfoVista
# next
# next
